In [1]:
import numpy as np

In [3]:
list = np.array([1,2,3])

In [4]:
list

array([1, 2, 3])

In [5]:
a = np.arange(1000)
%time a2 = a**2

Wall time: 999 µs


In [7]:
a*2 # array의 경우 각각의 a 원소에 값을 계산함

array([   0,    2,    4,    6,    8,   10,   12,   14,   16,   18,   20,
         22,   24,   26,   28,   30,   32,   34,   36,   38,   40,   42,
         44,   46,   48,   50,   52,   54,   56,   58,   60,   62,   64,
         66,   68,   70,   72,   74,   76,   78,   80,   82,   84,   86,
         88,   90,   92,   94,   96,   98,  100,  102,  104,  106,  108,
        110,  112,  114,  116,  118,  120,  122,  124,  126,  128,  130,
        132,  134,  136,  138,  140,  142,  144,  146,  148,  150,  152,
        154,  156,  158,  160,  162,  164,  166,  168,  170,  172,  174,
        176,  178,  180,  182,  184,  186,  188,  190,  192,  194,  196,
        198,  200,  202,  204,  206,  208,  210,  212,  214,  216,  218,
        220,  222,  224,  226,  228,  230,  232,  234,  236,  238,  240,
        242,  244,  246,  248,  250,  252,  254,  256,  258,  260,  262,
        264,  266,  268,  270,  272,  274,  276,  278,  280,  282,  284,
        286,  288,  290,  292,  294,  296,  298,  3

In [12]:
a1 = [i for i in range(1, 1000)]


In [16]:
print(a1*2) # list의 경우 a1을 그냥 2번 나열함

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 22

In [18]:
b = np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
c = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

In [22]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [23]:
print(c.ndim)

3


In [24]:
print(c.shape)

(2, 2, 2)


In [25]:
print(b.shape)

(2, 3)


In [26]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [27]:
a[0, :]

array([0, 1, 2, 3])

In [29]:
a[:, 1]

array([1, 5])

In [30]:
a [ a % 2 == 0 ]

array([0, 2, 4, 6])

In [31]:
# 뒤 함수에서 True라고 나온 친구들만 뽑음

In [37]:
a[np.array([0, 0])]

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [36]:
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [38]:
a = np.zeros(5)

In [39]:
a

array([ 0.,  0.,  0.,  0.,  0.])

In [40]:
a1 = np.zeros((3,3))
a1

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [43]:
a2 = np.ones((2,2))
a2

array([[ 1.,  1.],
       [ 1.,  1.]])

In [45]:
a3 = np.ones_like(a1) # np.zeros_like
a3

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [46]:
np.random.rand(3)

array([ 0.85633064,  0.88401538,  0.72802139])

In [48]:
np.random.rand(3,3)

array([[ 0.23801462,  0.0053857 ,  0.91720783],
       [ 0.83097621,  0.28630911,  0.8901733 ],
       [ 0.08814247,  0.10486478,  0.79840918]])

In [49]:
g = np.empty((4,3))
g

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [52]:
np.linspace(0, 10, 5) # start, end, 간격

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [53]:
np.random.seed(0)

In [54]:
np.random.rand(4)

array([ 0.5488135 ,  0.71518937,  0.60276338,  0.54488318])

In [55]:
np.random.randn(4) # 가우시안 정규분포

array([ 1.86755799, -0.97727788,  0.95008842, -0.15135721])

In [56]:
a = np.arange(12)

In [57]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
b = a.reshape(2,2,-1)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [61]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [62]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [63]:
y = x.reshape(5,1)
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [64]:
z = x[:, np.newaxis]
z

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [65]:
a1 = np.ones((2,3))
a2 = np.zeros((2,2))

In [66]:
a1

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [67]:
a2

array([[ 0.,  0.],
       [ 0.,  0.]])

In [68]:
np.hstack([a1,a2])

array([[ 1.,  1.,  1.,  0.,  0.],
       [ 1.,  1.,  1.,  0.,  0.]])

In [71]:
a3 = np.zeros((4,3))
a3

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [72]:
np.vstack([a1,a3])

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [73]:
# dstack은 축 방향으로 이동
# stack은 aixs 인수 사용 axis=0 행, axis=1 열

In [74]:
# r_ 메서드는 hstack과 유사한데 메서드임에도 불구하고 소괄호()를 사용하지 않고 대괄호 사용
np.r_[np.array([1,2,3]), 0, 0, np.array([4,3,5])]

array([1, 2, 3, 0, 0, 4, 3, 5])

In [75]:
a = np.array([0, 1, 2])
np.tile(a, 2)


array([0, 1, 2, 0, 1, 2])

### meshgrid

In [2]:
x = np.arange(3)
x

y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [3]:
X, Y = np.meshgrid(x, y)

In [97]:
for x, y in zip(X, Y):
    print(x, y)

[0 1 2] [0 0 0]
[0 1 2] [1 1 1]
[0 1 2] [2 2 2]
[0 1 2] [3 3 3]
[0 1 2] [4 4 4]


In [5]:
[list(zip(x, y)) for x, y in zip(X, Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

In [6]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [7]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [8]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [9]:
X = np.array([[11,12,13],[21,22,23]])
X

array([[11, 12, 13],
       [21, 22, 23]])

In [10]:
X.T

array([[11, 21],
       [12, 22],
       [13, 23]])