# (함수) shift + tap  -> 설명 나옴 

In [2]:
# numpy 라이브러리 설치 
import numpy as np

# IPython 패키지에 이미지 사용하기
# 주피터 노트북에 이미지 넣기 위함 
from IPython.display import Image

# 0. 데이터 형식 
### 실제로 연산이 될 때는 자료형이 알아서 연산됨, 출력시 참고
<img src="images/datatype_1.jpg" width="60%" height="60%" align="left">
string -> s 데이터타입 더 이상 없음   
string -> u


<img src="images/datatype_2.jpg" width="60%" height="60%" align="left">  


- int, float 등 : i, f로 줄여서 사용 
~~~python3
np.array( data, dtype = np.float63 )
np.array( data, dtype = 'i' )
~~~

- 문자열과 숫자형이 연산될 경우 -> string, but u1 형
현재 버전에서 S형 더 이상 없음

### 배열 내 데이터 타입 지정 

In [3]:
data = [1,2,3,4,5]
arr_dtype_float64 = np.array( data, dtype=np.float64 )
arr_dtype_f8 = np.array( data, dtype = 'f8')
print( arr_dtype_float64.dtype, arr_dtype_float64 )
print( arr_dtype_f8.dtype, arr_dtype_f8)

float64 [1. 2. 3. 4. 5.]
float64 [1. 2. 3. 4. 5.]


# 1. ndarray
- ndarray 클래스
    - __같은 자료형__으로 묶인 배열
- 배열  
    - 선언
        - np.array( data )  
        - np.aaray( data, dtype=np.int32 )

    - 타입
        - dtype : int8/uint8, int16,uint16.... 
        - 배열.dtype    : 배열 내부의 타입 확인   
    
    - 행렬 구조/차원 확인
        - __배열.shape__     : 배열의 행의 갯수, 열의 갯수 확인 ★
        - 배열.ndim     : 배열의 차원 확인
    
    - 함수 및 메소드
        - np.arange(#) : range(#)를 __ndarray로 반환__
        - len(배열)     : 배열의 행/열 확인
        - 배열.reshape(row, column) : 
  
    - 배열 생성 함수 ( 자주 사용되는 것 )
        - np.zeros(), np.ones()
            - 기본 dtype = 'float64' 
        - np.arange(#)
        - random.rand()    : 0 ~ 1 균일 분포   / 실수
        - random.randn()   : Gaussian RD     / 실수 
        - random.randint() : ( 시작, 끝, 배열 차원/크기 ) : 균일 분포 정수 난수
     
       
    - 배열 생성 함수 ( 자주 사용 안하는 것 ) 
        - zeros_like, ones_like
        - empty 
        - linspace, logspace
        
    - NumPy 통계함수 
        - len(배열) : 배열갯수
        - np.sum(배열)
        - np.mean(배열)
        - np.std(배열) : 표준편차 
        - np.var(배열  : 분산 
        - np.min(배열)
        - np.max(배열) 
        - np.argmin(배열)
        - np.argmax(배열)
        - np.cumsum(배열)   : 원소의 누적 합 
        - np.cumprod(배열)  : 원소의 누적 곱 
        - np.count(배열)
        - np.sum(배열)
        - np.abs(배열) : 각 원소의 절댓값 
        - 배열.t 
        - np.sqrt(배열)
        - np.exp(배열) 
        - np.log(배열) : base = e 
            - cf) np.log10, log2 ... 
        - 스칼라 ** 배열 : 배열 원소에 스칼라 제곱        
            - ex) 3 ** 배열 
        - 배열.T
        - np.dot(배열.T, 배열)  # dot product
        - np.ceil(배열)  : 올림 
        - np.floor(배열) : 내림
    - NumPy 난수생성
        - 데이터를 무작위로 섞거나, 임의의수, 난수를 발생시키는 random 서브패키지 사용 명령 
        - random.rand    : 0 ~ 1 균일 분포   / 실수
        - random.randn   : Gaussian RD     / 실수 
        - random.randint( 시작, 끝, 배열 차원/크기 ) : 균일 분포 정수 난수

In [4]:
a = np.array([1,2,3,4,5])
print(np.abs(a))

[1 2 3 4 5]


###  1.1. 1차원 배열

In [5]:
# 벡터화 연산 
# 1차원 배열 선언 
data1 = [1,2,3,4,5]
arr1 = np.array( data1 )
arr1

array([1, 2, 3, 4, 5])

### 1.2. 2차원 배열
- 선언 시, 행, 렬 맞춰서 입력 ( Readiblity ) 

In [6]:
data2 = [[1,2,3,4],
         [5,6,7,8]]
arr2 = np.array( data2 )
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 1.3. 3차원 배열  ( Layer, Row, Column ) 

In [7]:
#  2 x 3 x 4 배열 
# 행 x 열 x 깊이 
d = np.array([
    [
        [1,2,3,4],
        [5,6,7,8,],
        [9,10,11,12]
    ],
    [
        [13,14,15,16],
        [17,18,19,20],
        [21,22,23,24]
    ]
])
print(d, d.shape, sep='\n\n')
print(len(d)) 
print()

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

(2, 3, 4)
2



### 1.4. 배열.reshape(행, 열) 
- 배열 선언하고 reshape를 통해 행과 열에 맞게 변환  

In [8]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 1.5. shape, ndim 속성 배열의 차원과 크기 
- ndim : 배열의 차원 반환 
- shape : 행의 갯수, 열의 갯수 확인할 때 굉장히 많이 사용

In [9]:
ab = np.array([1,2,3])
print(ab.ndim)
print(ab.shape)

1
(3,)


In [10]:
abc = np.array([[1,2,3,],
                [4,5,6]])
print(abc.ndim)
print(abc.shape)

2
(2, 3)


### 1.6. len : 해당 배열 원소의 갯수 
- shape가 더 직관적으로 확인 가능  

In [11]:
arr2 = np.array([[1,2,3],
                 [3,4,6]])
len(arr2)

2

In [12]:
len(arr2[0])

3

In [13]:
arr2.shape

(2, 3)

### 1.7. np.array( data, dtype=type ) 

data3 = [1.3, 1.5, 1.7]
arr_dtype_int8 = np.array( data3, dtype=np.int8 )
arr_dtype_int8

### 1.8. 배열의 데이터 타입 확인 

In [14]:
arr1.dtype 

dtype('int64')

### 1.9. 배열의 차원 확인 : 1차원 배열

In [15]:
arr1.shape

(5,)

### 1.10. 배열의 차원 확인 : 2차원 배열

In [16]:
arr2.shape

(2, 3)

### 1.11. 배열의 벡터화 연산 

In [17]:
# Broadcasting :Scalar * Vector 
a = np.array([1,2,3])
b = np.array([10,20,30])
2 * a + b

array([12, 24, 36])

### 1.12. np.arange로 배열 만들기 

In [18]:
# arange(#) : range(0,#) 을 
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 2. Bollean Indexing ( 불리안 마스크 ) 
- and 연산 : &
- or  연산 : |

In [19]:
arr1 = np.array([1,2,3])
arr1 == 2

array([False,  True, False])

In [20]:
arr2 = np.array([10,11,12])
arr2 > 10

array([False,  True,  True])

In [21]:
( arr1 == 2 ) & ( arr2 > 10 ) 

#    결과값                  ∇∇
#    arr1 == 2 : [ False, True, False ] 
#    arr2 > 10 : [ False, True, True  ]
#                [ False, True ,False ]

array([False,  True, False])

# 3. 슬라이싱 
- numpy에서 슬라이스 객체는 원본 객체를 참조
    + 슬라이스 객체에 값 할당 시 원본 변화 ★
- 파이썬 슬라이스 객체 : 반복 가능한 객체만 할당 가능 

### 3.1. NumPy 슬라이스 객체 : 1차원 배열
- 슬라이스 해온 배열 객체 계속 참조

In [22]:
arr = np.arange(10)
arr_slice = arr[0:3] # 슬라이스 객체 생성 
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr_slice[0] = 1234
arr

array([1234,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [24]:
arr_slice[:] = -10
arr

array([-10, -10, -10,   3,   4,   5,   6,   7,   8,   9])

### 3.2. NumPy 슬라이스 객체 : 2차원 배열

<img src="images/2dslice.jpg" width="50%" height="50%" align="left">

In [25]:
arr = np.arange(8).reshape(2,4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

### 3.3. 첫번째 행 전체

In [26]:
arr[0,:] 

array([0, 1, 2, 3])

### 3.4. 두번째 '열' 전체

In [27]:
arr[:,1]  # arr[ 전체행, 1열 ]

array([1, 5])

### 3.5. 첫번째 행 2열, 두번째 행 2열 

In [28]:
arr[:2,:2] # arr[ ~ 2번째 행 , ~2번째 열]

array([[0, 1],
       [4, 5]])

# 4. 불리언 인덱싱 

### 4.1. 배열의 불리언 인덱싱  #1 

In [29]:
a = np.array([0,1,2,3,4])
idx = np.array([True, False, True, False, True])
a[idx]

array([0, 2, 4])

### 4.2. 배열의 불리언 인덱싱 #2

In [30]:
a % 2        # array([0, 1, 0, 1, 0])
a % 2 == 0   # array([ True, False,  True, False,  True])
a[a % 2 == 0]#array([0, 2, 4])

array([0, 2, 4])

# 5. Transposing Arrays and Swapping Axes
- 배열.T
- np.dot(배열.T, 배열) 

### 5.1. 1차원 배열
- 배열.T : MｘN ➤ NｘM

In [31]:
arr = np.arange(6).reshape(3,2)
print( arr.shape, arr, sep = '\n\n')

(3, 2)

[[0 1]
 [2 3]
 [4 5]]


In [32]:
print( arr.T.shape, arr.T, sep = '\n\n')

(2, 3)

[[0 2 4]
 [1 3 5]]


### 5.2. 2차원 배열 

In [33]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [34]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### 5.3. N- Dimensional Tensor Transpose
- np.transpose( array, (axes) )
- ex) ( i, j, k ) -> axes(1, 2, 0) -> ( j, k, i ) 

In [35]:
arr3 = np.arange(12).reshape(2,2,3)
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [36]:
arr4 = np.transpose(arr3, (1,2,0))
arr4

array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])

<img src = "images/nd_tensor_transpose.jpg" width="60%" height="60%" align ="left">

### 5.4. Dot Product : inner Matrix Product - XᵀX
- XᵀX

### 5.4.1. random m x n matrix 생성
- np.random.randn( m, n )

In [64]:
arr = np.random.randn(6, 3)   # 6 x 3 random matrix generater
print( arr ) 

[[ 1.91382039  0.33079713  1.14194252]
 [-1.12959516 -0.85005238  0.96082   ]
 [-0.21741818  0.15851488  0.87341823]
 [-0.11138337 -1.03803876 -1.00947983]
 [-1.05825656  0.65628408 -0.06249159]
 [-1.73865429  0.103163   -0.62166685]]


#### 5.4.2. XᵀX
- np.dot(Xᵀ, X) 

In [65]:
print( np.dot(arr.T, arr) )

[[9.14119633 0.80057586 2.16967339]
 [0.80057586 2.37601863 0.64218771]
 [2.16967339 0.64218771 4.3994916 ]]


# 6. 배열 생성 함수 
- 자주 사용되는 것 
    - zeros, ones
        - 기본 dtype = 'float64' 
    - arange
    - rand, randn 
    - np.sqrt(np.array)
    - np.exp(np.array) 
     
- 잘 사용 안하는 것
    - zeros_like, ones_like
    - empty 
    - linspace, logspace

### 6.1. np.zeros

In [39]:
z1 = np.zeros(3, dtype = 'i') # 정수형
z2 = np.zeros((2,3))          # default : 실수형
print(z1, z2, sep='\n\n')

[0 0 0]

[[0. 0. 0.]
 [0. 0. 0.]]


### 6.2. np.ones

In [40]:
o1 = np.ones(3, dtype = 'i') # 정수형
o2 = np.ones((2,3))          # default : 실수형
print(o1, o2, sep='\n\n')

[1 1 1]

[[1. 1. 1.]
 [1. 1. 1.]]


### 6.3. np.arange( # )  / np.arange(start, end, stride)

In [41]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

# 7. 벡터 연산 함수

<img src="images/unary_func_1.jpg" height="50%" width="50%" align="left">
<img src="images/unary_func_2.jpg" height="50%" width="50%" align="left">

### 7.1 덧셈

In [43]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)
x, y

(array([    1,     2,     3, ...,  9998,  9999, 10000]),
 array([10001, 10002, 10003, ..., 19998, 19999, 20000]))

In [44]:
z = x + y
z

array([10002, 10004, 10006, ..., 29996, 29998, 30000])

### 7.2 지수, 제곱, 로그함수 
- np.exp(array)
- 스칼라 값 ** 배열 
- np.log(array) : base = e
    - np.log2(array) / np.log10(array) ....

# 8. 브로드캐스팅 개념 
- 서로 다른 크기를 가진 두 배열의 "사칙 연산"에서, 크기가 작은 배열이 큰 배열에 맞춤 
~~~python
'''              ∇ broadcasting    
[[0 1 2]           
 [1 2 3]    +    [0 1 2]    
 [2 3 4]         
 [4 5 6]]        
                   ∇ broadcasting    
[[0 1 2]       [0 1 2]   
 [1 2 3]        [0 1 2]    
 [2 3 4]        [0 1 2]       
 [4 5 6]]       [0 1 2]    
'''
~~~

### 8.1. Broadcasting 연산    


In [45]:
x = np.array([
    [0,1,2],
    [1,2,3],
    [2,3,4],
    [4,5,6]
])

y = np.arange(3)

x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [46]:
y

array([0, 1, 2])

In [47]:
# '''                ∇ broadcasting    
# [[0 1 2]        [0 1 2]   
#  [1 2 3]   +    [0 1 2]    
#  [2 3 4]        [0 1 2]       
#  [4 5 6]]       [0 1 2]    
# '''

# 9. 1차원 배열의 차원축소 연산 
- 하나의 행에 있는 원소들을 하나의 데이터 집합으로, 그 집합의 평균을 구하여 1차원 벡터로 반환 
- NumPy 차원 축소 연산 메서드 
    - 배열.sum() / np.sum(배열)
    - 배열.mean()/ np.mean(배열) 
    - 최대/최소      : max min 
    - 최대/최소 인덱스 : argmin / argmax 
    - np.median(배열) 
- 2차원 이상인 경우, axis를 인자로 사용 가능  

<img src="images/stastical_methods.jpg" height="60%" width="60%" align="left" marging-left="50">

### 9.1. 중앙값 

In [48]:
a = np.array([[1,2,3,4],
              [5,6,7,8]])
np.median(a, axis=0)

array([3., 4., 5., 6.])

### 9.2. 합 ..

In [49]:
np.sum(x)

33

### 9.3. 최소(argmin), 최대(argmax) 인덱스 반환 

In [50]:
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [51]:
np.argmin(x)

0

In [52]:
np.argmax(x)

11

# 10. 2차원 배열의 차원축소 연산 
- 연산의 대상이 2차원 이상인 경우, 어느 차원으로 계산을 할 지 axis인수 이용 
- axis = 0 : 열 연산 
- axis = 1 : 행 연산 
- default : axis = 0 

In [53]:
x = np.array([
    [1,3],
    [2,4]
])
x

array([[1, 3],
       [2, 4]])

In [54]:
print(x.mean(axis = 0))  # 열 기준 계산

[1.5 3.5]


In [55]:
print(x.mean(axis = 1))  # 행 기준 계산

[2. 3.]


# 10.1. NumPy 통계함수 
- len(배열) : 배열갯수
- np.sum(배열)
- np.mean(배열)
- np.std(배열) : 표준편차 
- np.var(배열  : 분산 
- np.min(배열)
- np.max(배열) 
- np.argmin(배열)
- np.argmax(배열)
- np.cumsum(배열)   : 원소의 누적 합 
- np.cumprod(배열)  : 원소의 누적 곱 

In [56]:
x = np.random.randn(10)
x

array([ 0.4179261 ,  0.76111678, -0.27872852,  0.25414537, -1.71715061,
       -0.04550265,  0.23579545, -0.06382069, -0.36427533,  0.3922232 ])

In [57]:
len(x)        # 데이터 갯수 

10

In [58]:
np.mean(x)    # 평균 

-0.0408270906475313

In [59]:
np.var(x)

0.4176456771384192

# 11. NumPy 난수생성
- 데이터를 무작위로 섞거나, 임의의수, 난수를 발생시키는 random 서브패키지 사용 명령 
    - random.rand    : 0 ~ 1 균일 분포   / 실수
    - random.randn   : Gaussian RD     / 실수 
    - random.randint( 시작, 끝, 배열 차원/크기 ) : 균일 분포 정수 난수

In [60]:
np.random.seed(1)   
np.random.rand(10)   # seed를 이용한 배열 

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01,
       3.96767474e-01, 5.38816734e-01])

In [61]:
np.random.rand(3,2)  # m x n 난수 배열 생성

array([[0.41919451, 0.6852195 ],
       [0.20445225, 0.87811744],
       [0.02738759, 0.67046751]])

In [62]:
np.random.randint(10, 20, size = 10)   

array([17, 17, 19, 11, 17, 10, 16, 19, 19, 17])

In [1]:
np.random.randint(10, 20, size = (3,5))   

NameError: name 'np' is not defined